import { app, BrowserWindow, ipcMain, session, powerSaveBlocker, dialog } from 'electron';
import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { MipDatabase } from './database/db.js';
import { profiles, validateProfile, resolveProfile, requestInstruction, assignOutcome, DeterministicRNG, timingPlan, analyzeStream, sha256, canonical } from '../../src/engine.js';
import { PRESETS, quickRecipe, validateRecipe } from '../../src/audio.js';

const here = path.dirname(fileURLToPath(import.meta.url)); let db; let mainWindow; const active = new Map(); let blocker = null;
const getId = payload => { if (!payload || typeof payload.id !== 'string' || !/^S\d{4,}$/.test(payload.id)) throw new Error('Invalid session identifier.'); return payload.id; };
function createWindow(){mainWindow=new BrowserWindow({width:1440,height:940,minWidth:1050,minHeight:700,show:false,icon:path.join(here,'..','..','..','build','icon.ico'),webPreferences:{preload:path.join(here,'..','preload','preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});mainWindow.once('ready-to-show',()=>mainWindow.show());mainWindow.webContents.setWindowOpenHandler(()=>({action:'deny'}));mainWindow.webContents.on('will-navigate',e=>e.preventDefault());mainWindow.loadFile(path.join(here,'..','..','public','index.html'));}
function register(){
  ipcMain.handle('profiles:list',()=>Object.values(profiles).map(p=>({...p,validation:validateProfile(p)})));
  ipcMain.handle('audio:presets',()=>Object.values(PRESETS));
  ipcMain.handle('audio:quick',(_,v)=>{const recipe=quickRecipe(v.centerHz,v.beatHz);return{recipe,validation:validateRecipe(recipe)}});
  ipcMain.handle('sessions:list',()=>db.listSessions());
  ipcMain.handle('sessions:get',(_,p)=>{const id=getId(p),s=db.db.prepare('SELECT * FROM sessions WHERE session_id=?').get(id);if(!s)throw Error('Session not found.');const reveal=!!db.db.prepare('SELECT 1 FROM raw_reports_locked WHERE session_id=?').get(id),commit=db.db.prepare('SELECT config_hash FROM session_commitments WHERE session_id=?').get(id),profile=profiles[s.profile_id];return{sessionId:s.session_id,createdUtc:s.created_utc,participantLabel:s.participant_label,recordType:s.record_type,profileId:s.profile_id,profileVersion:s.profile_version,status:s.status,revealPolicy:s.reveal_policy,configFingerprint:commit?.config_hash,configSnapshot:profile||null,hiddenObjective:reveal?Number(s.hidden_objective):undefined,participantTarget:reveal?s.participant_target:undefined,revealEligible:reveal,analysis:reveal?JSON.parse(db.db.prepare('SELECT payload_json FROM analyses WHERE session_id=?').get(id)?.payload_json||'null'):null,audioArtifact:profile?.audio||null}});
  ipcMain.handle('sessions:events',(_,p)=>db.events(getId(p)));
  ipcMain.handle('sessions:verify',(_,p)=>db.verify(getId(p)));
  ipcMain.handle('sessions:output',(_,p)=>{const id=getId(p);if(!db.db.prepare('SELECT 1 FROM raw_reports_locked WHERE session_id=?').get(id))throw Error('Machine output remains hidden until the raw report is locked.');return db.db.prepare('SELECT * FROM machine_outputs WHERE session_id=? ORDER BY output_seq').all(id)});
  ipcMain.handle('sessions:create',(_,p)=>{const profile=resolveProfile(p.profileId||'BASELINE_NOW_BINARY_V1');const objective=assignOutcome(profile,new DeterministicRNG(`session-${Date.now()}-${process.hrtime.bigint()}`)),s=db.beginSession(profile,p.participantLabel||'Local participant',p.recordType||'dry');db.db.prepare('UPDATE sessions SET hidden_objective=?,participant_target=? WHERE session_id=?').run(String(objective),requestInstruction(profile,objective),s.id);active.set(s.id,{profile,objective,trial:s.trial,seed:p.seed||'session-seed',timing:timingPlan(profile)});return{sessionId:s.id,trialId:s.trial,participantTarget:requestInstruction(profile,objective),timing:timingPlan(profile),status:'Committed'}});
  ipcMain.handle('sessions:start',(_,p)=>{const id=getId(p);if(p.memoryConfirmed!==true)throw Error('Explicit memory confirmation is required before START.');const state=active.get(id);if(!state)throw Error('Session runtime unavailable; restart from a committed profile.');if(state.running)return{sessionId:id,status:'Running',hidden:true};state.running=true;state.cancelled=false;db.appendEvent(id,state.trial,'STARTED',{timing:state.timing});db.appendEvent(id,state.trial,'AUDIO_READY',{recipeId:state.profile.audio.recipeId,engine:'AudioWorklet',handshake:'main-authority'});if(blocker===null)blocker=powerSaveBlocker.start('prevent-app-suspension');const total=(state.profile.output.preBlocks+state.profile.output.primaryBlocks+state.profile.output.postBlocks)*(state.profile.output.blockSize||1);state.total=total;state.values=[];state.rng=new DeterministicRNG(state.seed);const step=()=>{if(state.cancelled)return;const end=Math.min(state.values.length+128,total);for(let i=state.values.length;i<end;i++){const value=assignOutcome(state.profile,state.rng);state.values.push(value);db.db.prepare('INSERT INTO machine_outputs VALUES(?,?,?,?,?,?,?,?,?)').run(id,state.trial,i,new Date().toISOString(),process.hrtime.bigint().toString(),JSON.stringify(value),i<total/3?'pre':i<total*2/3?'primary':'post',sha256(canonical({id,i,value})))}if(state.values.length<total){setImmediate(step);return;}const analysis=analyzeStream({requested:state.objective,values:state.values,primary:[Math.floor(total/3),Math.floor(total*2/3)],exploratory:[[0,Math.floor(total/3)],[Math.floor(total*2/3),total]]});db.db.prepare('INSERT OR REPLACE INTO analyses(session_id,analysis_version,input_hash,payload_json,created_utc) VALUES(?,?,?,?,?)').run(id,'analysis-v1',sha256(state.values.join(',')),JSON.stringify(analysis),new Date().toISOString());db.appendEvent(id,state.trial,'RETURN_CONFIRMED',{generatedFrames:total});db.db.prepare('UPDATE sessions SET status=? WHERE session_id=?').run('RETURNED',id);state.running=false;if(blocker!==null){powerSaveBlocker.stop(blocker);blocker=null;}};setImmediate(step);return{sessionId:id,status:'Running',hidden:true,reportRequired:true}});
  ipcMain.handle('reports:draft',(_,p)=>{const id=getId(p);db.db.prepare('INSERT OR REPLACE INTO raw_report_drafts VALUES(?,?,?)').run(id,new Date().toISOString(),JSON.stringify(p.report||{}));db.appendEvent(id,null,'RAW_REPORT_DRAFT_SAVED',{});return{saved:true}});
  ipcMain.handle('reports:lock',(_,p)=>{const id=getId(p),now=new Date().toISOString(),payload=JSON.stringify(p.report||{}),hash=sha256(payload),tx=db.db.transaction(()=>{db.db.prepare('INSERT INTO raw_reports_locked VALUES(?,?,?,?,?)').run(id,now,payload,hash,'1.0');db.db.prepare('DELETE FROM raw_report_drafts WHERE session_id=?').run(id);db.appendEvent(id,null,'RAW_REPORT_LOCKED',{lockHash:hash});db.db.prepare('UPDATE sessions SET status=? WHERE session_id=?').run('REVEAL_ELIGIBLE',id)});tx();return{locked:true,lockHash:hash}});
  ipcMain.handle('sessions:reveal',(_,p)=>{const id=getId(p),m=db.db.prepare('SELECT * FROM sessions WHERE session_id=?').get(id);if(!db.db.prepare('SELECT 1 FROM raw_reports_locked WHERE session_id=?').get(id))throw Error('Reveal is not eligible until the raw report is locked.');db.appendEvent(id,null,'REVEALED',{objective:m.hidden_objective});db.db.prepare('UPDATE sessions SET status=? WHERE session_id=?').run('REVEALED',id);return{objective:Number(m.hidden_objective),participantTarget:m.participant_target,analysis:JSON.parse(db.db.prepare('SELECT payload_json FROM analyses WHERE session_id=?').get(id)?.payload_json||'null'),integrity:db.verify(id)}});
  ipcMain.handle('settings:get',()=>({appVersion:app.getVersion(),engineVersion:'1.2.0',schemaVersion:1,databasePath:db.file,databaseSize:fs.statSync(db.file).size,lastBackup:db.db.prepare('SELECT * FROM backups ORDER BY created_utc DESC LIMIT 1').get()||null}));
  ipcMain.handle('backup:create',()=>{const id=`B${Date.now()}`,target=path.join(db.backupDir,`${id}.sqlite3`);db.db.pragma('wal_checkpoint(TRUNCATE)');fs.copyFileSync(db.file,target);const hash=sha256(fs.readFileSync(target));db.db.prepare('INSERT INTO backups VALUES(?,?,?,?,?)').run(id,new Date().toISOString(),target,hash,1);return{id,path:target,sha256:hash,verified:true}});
  ipcMain.handle('exports:session',async(_,p)=>{const id=getId(p),m=db.db.prepare('SELECT * FROM sessions WHERE session_id=?').get(id),dir=path.join(db.exportDir,id);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(m,null,2));fs.writeFileSync(path.join(dir,'events.json'),JSON.stringify(db.events(id),null,2));fs.writeFileSync(path.join(dir,'integrity.json'),JSON.stringify(db.verify(id),null,2));return{directory:dir}});
  ipcMain.handle('audio:health',(_,p)=>({status:'software-check-complete',recipeId:p?.recipeId||'A-U396-4',context:'AudioWorklet required',note:'Physical headphone acoustics require owner assessment.'}));
  ipcMain.handle('audio:block',(_,p)=>({accepted:true,bytes:p?.byteLength||0}));
}
app.whenReady().then(()=>{db=new MipDatabase(app.getPath('userData'));register();session.defaultSession.webRequest.onHeadersReceived((details,callback)=>callback({responseHeaders:{...details.responseHeaders,'Content-Security-Policy':["default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self'; media-src 'self' blob:; object-src 'none'; base-uri 'none'; frame-ancestors 'none'"]}}));createWindow();app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)createWindow()})});app.on('window-all-closed',()=>{if(blocker)powerSaveBlocker.stop(blocker);db?.close();if(process.platform!=='darwin')app.quit()});
