import fs from 'node:fs';
import path from 'node:path';
import { profiles, DeterministicRNG, assignOutcome, analyzeStream, resolveProfile, sha256, canonical } from '../src/engine.js';
import { PRESETS, renderWav, writeArtifact } from '../src/audio.js';
import { Storage } from '../src/storage.js';

const root = path.resolve(process.env.MIP_DRY_ROOT || './runtime/dry-run'); fs.rmSync(root, { recursive: true, force: true }); fs.mkdirSync(root, { recursive: true });
const storage = new Storage(root); const artifacts = {};
for (const [id, recipe] of Object.entries(PRESETS)) artifacts[id] = writeArtifact(storage.artifacts, recipe, 0.1);
const layered = { ...PRESETS['A-U396-4'], id: 'LAYERED_HEMISYNC_DEMO_V1', version: 1, provenance: 'PATENT_GROUNDED_RECONSTRUCTION', mode: 'PHASED_PINK_PATENT_5356368', carriers: [{ leftHz:394,rightHz:398,gain:.2 }, { leftHz:200,rightHz:204,gain:.08 }], septon: [{leftHz:100,rightHz:101.5,gain:.04},{leftHz:200,rightHz:204,gain:.04}], noise: { algorithm:'PHASED_PINK_PATENT_5356368', seed: 5356368, gain: .03, sweepHz: .125, rightPhase: Math.PI/2 } };
artifacts.layered = writeArtifact(storage.artifacts, layered, 0.1);
const p = resolveProfile('BASELINE_NOW_BINARY_V1'), session = storage.createSession({ profile:p, participantLabel:'Dry-run harness', recordType:'dry' }), rng = new DeterministicRNG('dry-immediate'); const objective = assignOutcome(p, rng); storage.appendEvent(session.sessionId,'COMMITTED',{objective,configFingerprint:session.manifest.configFingerprint}); storage.appendEvent(session.sessionId,'STARTED'); const values=Array.from({length:32},()=>assignOutcome(p,rng)); values.forEach((value,index)=>storage.appendOutput(session.sessionId,{index,value,block:index<10?'pre':index<22?'primary':'post',scheduledUtc:new Date().toISOString()})); const analysis=analyzeStream({requested:objective,values,primary:[10,22],exploratory:[[0,10],[22,32]]}); storage.appendEvent(session.sessionId,'RETURN_CONFIRMED',{analysis}); storage.lockRawReport(session.sessionId,{subjectiveDuration:'Unknown',stateIntensity:'5',modality:'combined',notes:'Automated no-participant dry run'}); storage.updateManifest(session.sessionId,{status:'Revealed',actualObjectiveState:objective,participantTarget:String(objective),analysis}); storage.appendEvent(session.sessionId,'REVEALED',{objective}); const integrity=storage.verify(session.sessionId); const report={reportVersion:'report-v1',sessionId:session.sessionId,profileId:p.id,status:'Revealed',objective,analysis,integrity,audioFixtures:Object.fromEntries(Object.entries(artifacts).map(([k,v])=>[k,{wav:v.wavPath,manifest:v.manifestPath,verification:v.verificationPath,hashes:v.hashes}]))}; fs.writeFileSync(path.join(root,'dry-run-report.json'),JSON.stringify(report,null,2)); console.log(JSON.stringify({root,sessionId:session.sessionId,integrity,audioFixtures:Object.keys(artifacts),report:path.join(root,'dry-run-report.json')},null,2));
