import fs from 'node:fs';
import path from 'node:path';
import { canonical, sha256, APP_VERSION, ENGINE_VERSION } from './engine.js';

export class Storage {
  constructor(root = path.resolve(process.env.MIP_DATA_ROOT || './runtime')) { this.root = root; this.sessions = path.join(root, 'sessions'); this.artifacts = path.join(root, 'audio-artifacts'); fs.mkdirSync(this.sessions, { recursive: true }); fs.mkdirSync(this.artifacts, { recursive: true }); this.recoverIncompleteSessions(); }
  recoverIncompleteSessions() { for (const id of fs.readdirSync(this.sessions)) { if (!/^S\d+$/.test(id)) continue; try { const m = this.readManifest(id), events = fs.existsSync(path.join(this.sessions,id,'events.jsonl')) ? fs.readFileSync(path.join(this.sessions,id,'events.jsonl'),'utf8') : ''; if (['Draft','Committed','Running'].includes(m.status) && !events.includes('RETURN_CONFIRMED')) this.updateManifest(id, { status: 'Incomplete', recovery: { detectedUtc: new Date().toISOString(), reason: 'No terminal return confirmation found; evidence preserved.' } }); } catch { /* preserve unreadable bundles for explicit integrity review */ } } }
  nextSessionId() { let max = 0; const roots = [this.sessions, path.resolve('sessions')]; for (const root of roots) { if (!fs.existsSync(root)) continue; for (const name of fs.readdirSync(root)) { const m = /^S(\d{4,})$/.exec(name); if (m) max = Math.max(max, Number(m[1])); } } return `S${String(max + 1).padStart(4, '0')}`; }
  createSession({ profile, participantLabel = 'Local participant', recordType = 'dry' }) { let sessionId, dir; for (let attempt = 0; attempt < 100; attempt++) { sessionId = this.nextSessionId(); dir = path.join(this.sessions, sessionId); try { fs.mkdirSync(dir, { recursive: false }); break; } catch (error) { if (error.code !== 'EEXIST') throw error; } } if (!dir || !fs.existsSync(dir)) throw new Error('Unable to allocate an exclusive session ID'); const trialId = `${sessionId}-T001`; const manifest = { schemaVersion: '1.0', sessionId, primaryTrialId: trialId, blockId: null, createdUtc: new Date().toISOString(), appVersion: APP_VERSION, engineVersion: ENGINE_VERSION, participantLabel, sessionClass: 'COMMUNICATION', recordType, profileId: profile.id, profileVersion: profile.version, status: 'Draft', revealPolicy: profile.reveal.policy, integritySchemaVersion: 'hash-chain-v1', configSnapshot: profile, configFingerprint: sha256(canonical(profile)) }; fs.writeFileSync(path.join(dir, 'manifest.json'), JSON.stringify(manifest, null, 2)); fs.writeFileSync(path.join(dir, 'events.jsonl'), ''); fs.writeFileSync(path.join(dir, 'machine-output.jsonl'), ''); return { sessionId, trialId, dir, manifest }; }
  readManifest(id) { return JSON.parse(fs.readFileSync(path.join(this.sessions, id, 'manifest.json'), 'utf8')); }
  updateManifest(id, patch) { const current = this.readManifest(id); const next = { ...current, ...patch }; fs.writeFileSync(path.join(this.sessions, id, 'manifest.json'), JSON.stringify(next, null, 2)); return next; }
  appendEvent(id, type, data = {}) { const dir = path.join(this.sessions, id), file = path.join(dir, 'events.jsonl'); const lines = fs.existsSync(file) ? fs.readFileSync(file, 'utf8').trim().split('\n').filter(Boolean) : []; const previousHash = lines.length ? JSON.parse(lines.at(-1)).hash : 'GENESIS'; const event = { seq: lines.length + 1, eventId: `${id}-E${String(lines.length + 1).padStart(5, '0')}`, type, occurredUtc: new Date().toISOString(), monotonicMs: Number(process.hrtime.bigint() / 1000000n), data, previousHash }; event.hash = sha256(canonical(event)); fs.appendFileSync(file, JSON.stringify(event) + '\n'); return event; }
  appendOutput(id, record) { const file = path.join(this.sessions, id, 'machine-output.jsonl'); const line = { ...record, recordHash: sha256(canonical(record)) }; fs.appendFileSync(file, JSON.stringify(line) + '\n'); return line; }
  lockRawReport(id, report) { const dir = path.join(this.sessions, id); const draftPath = path.join(dir, 'raw-report.draft.json'); const locked = { schemaVersion: '1.0', lockedUtc: new Date().toISOString(), report: JSON.parse(JSON.stringify(report)) }; locked.lockHash = sha256(canonical(locked)); fs.writeFileSync(path.join(dir, 'raw-report.locked.json'), JSON.stringify(locked, null, 2)); if (fs.existsSync(draftPath)) fs.unlinkSync(draftPath); this.appendEvent(id, 'RAW_REPORT_LOCKED', { lockHash: locked.lockHash }); this.updateManifest(id, { status: 'Raw Report Locked', rawReportLockHash: locked.lockHash }); return locked; }
  saveDraft(id, report) { fs.writeFileSync(path.join(this.sessions, id, 'raw-report.draft.json'), JSON.stringify({ savedUtc: new Date().toISOString(), report }, null, 2)); this.appendEvent(id, 'RAW_REPORT_DRAFT_SAVED'); }
  revealEligible(id) { const m = this.readManifest(id); if (m.revealPolicy === 'AFTER_RAW_REPORT_LOCK') return fs.existsSync(path.join(this.sessions, id, 'raw-report.locked.json')); if (m.revealPolicy === 'AFTER_BLOCK_LOCK') return m.blockLocked === true; if (m.revealPolicy === 'DELAYED_DATETIME') return Date.now() >= Date.parse(m.revealAtUtc); return false; }
  verify(id) { const dir = path.join(this.sessions, id), errors = []; const eventFile = path.join(dir, 'events.jsonl'); let previous = 'GENESIS', count = 0; if (fs.existsSync(eventFile)) for (const line of fs.readFileSync(eventFile, 'utf8').split('\n').filter(Boolean)) { count++; const event = JSON.parse(line), hash = event.hash; const copy = { ...event }; delete copy.hash; if (event.previousHash !== previous || sha256(canonical(copy)) !== hash) errors.push(`Event ${event.seq} hash chain mismatch`); previous = hash; } const outputFile = path.join(dir, 'machine-output.jsonl'); let outputCount = 0; if (fs.existsSync(outputFile)) outputCount = fs.readFileSync(outputFile, 'utf8').split('\n').filter(Boolean).length; const manifest = this.readManifest(id); const result = { valid: errors.length === 0, errors, eventCount: count, machineOutputCount: outputCount, configFingerprint: manifest.configFingerprint, rawReportLocked: fs.existsSync(path.join(dir, 'raw-report.locked.json')) }; fs.writeFileSync(path.join(dir, 'integrity.json'), JSON.stringify(result, null, 2)); return result; }
  listSessions() { return fs.readdirSync(this.sessions).filter(x => /^S\d+$/.test(x)).map(id => this.readManifest(id)).sort((a, b) => b.createdUtc.localeCompare(a.createdUtc)); }
  sessionFiles(id) { return fs.readdirSync(path.join(this.sessions, id)); }
  load(id, file) { const safe = path.basename(file); return fs.readFileSync(path.join(this.sessions, id, safe), 'utf8'); }
}
